---
- name: Add elasticsearch apt key
  apt_key:
    url: https://packages.elastic.co/GPG-KEY-elasticsearch
    state: present
  sudo: yes

- name: Add elasticsearch repository
  apt_repository:
    repo: "deb https://packages.elastic.co/elasticsearch/{{elasticsearch_version}}/debian stable main"
    state: present
    update_cache: yes
  sudo: yes

- name: Install elasticsearch
  apt: pkg=elasticsearch state=present
  sudo: yes

- name: Start elasticsearch
  service: name=elasticsearch state=started enabled=yes
  sudo: yes
